test

diff --git a/.github/workflows/cp.yml b/.github/workflows/cp.yml
--- a/.github/workflows/cp.yml
+++ b/.github/workflows/cp.yml
@@ -1,4 +1,4 @@
-name: Run cp
+name: Run Deploying
 on:
   push:
     branches:
@@ -22,6 +22,14 @@ jobs:
       uses: actions/setup-node@v3.5.1
       with:
         node-version: "16"
+    - name: Check disk space
+      run: |
+        AVAILABLE_SPACE=$(df / | awk 'NR==2 {print $4}')
+        echo "Available space: $AVAILABLE_SPACE"
+        if [ $AVAILABLE_SPACE -lt 1048576 ]; then
+          echo "Error: Less than 1GB of disk space available"
+          exit 1
+        fi
 
     - name: copyfile-js
       run: sudo cp -rf ./js/* /usr/local/kong/js-plugins
