test

diff --git a/.github/workflows/cp.yml b/.github/workflows/cp.yml
--- a/.github/workflows/cp.yml
+++ b/.github/workflows/cp.yml
@@ -11,7 +11,22 @@ on:
 
 
 jobs:
+  Check disk space:
+    runs-on: kong
+    name: Check disk space
+    environment: play
+    steps:
+    - name: Check disk space
+      run: |
+        AVAILABLE_SPACE=$(df / | awk 'NR==2 {print $4}')
+        echo "Available space: $AVAILABLE_SPACE"
+        if [ $AVAILABLE_SPACE -lt 4271040 ]; then
+          echo "Error: Less than 1GB of disk space available"
+          exit 1
+        fi
+
   deploy-cp-js:
+    needs: Check disk space
     runs-on: kong
     name: Deploying Kong cp
     environment: play
