test

diff --git a/.github/workflows/def.yml b/.github/workflows/def.yml
--- a/.github/workflows/def.yml
+++ b/.github/workflows/def.yml
@@ -1,76 +1,76 @@
-name: Run deck-def
-on:
-  # workflow_run:
-  #       workflows: ["Run js-plugins"]
-  #       branches: [main]
-  #       types: [completed]
-  push:
-    branches:
-      - 'main'
-    paths:      
-      - 'deck/**'
-env:
-  DEF_CHANGED: ${{ github.event_name == 'push' }}
-  CP_CONF_CHANGED: ${{ contains(github.event.commits[0].modified, 'kong-conf/') }}
-  JS_CHANGED: ${{ contains(github.event.commits[0].modified, 'js/') }}
+# name: Run deck-def
+# on:
+#   # workflow_run:
+#   #       workflows: ["Run js-plugins"]
+#   #       branches: [main]
+#   #       types: [completed]
+#   push:
+#     branches:
+#       - 'main'
+#     paths:      
+#       - 'deck/**'
+# env:
+#   DEF_CHANGED: ${{ github.event_name == 'push' }}
+#   CP_CONF_CHANGED: ${{ contains(github.event.commits[0].modified, 'kong-conf/') }}
+#   JS_CHANGED: ${{ contains(github.event.commits[0].modified, 'js/') }}
 
-jobs:
-  # check_run:
-  #     runs-on: kong
-  #     outputs:
-  #       should_run: ${{ steps.check.outputs.should_run }}
-  #     steps:
-  #       - id: check
-  #         name: Check if def changed
-  #         run: |
-  #           if [[ "${{ env.DEF_CHANGED }}" == "true" ]]; then
-  #             echo "::set-output name=should_run::true"
-  #           else
-  #             echo "::set-output name=should_run::false"
-  #           fi
+# jobs:
+#   # check_run:
+#   #     runs-on: kong
+#   #     outputs:
+#   #       should_run: ${{ steps.check.outputs.should_run }}
+#   #     steps:
+#   #       - id: check
+#   #         name: Check if def changed
+#   #         run: |
+#   #           if [[ "${{ env.DEF_CHANGED }}" == "true" ]]; then
+#   #             echo "::set-output name=should_run::true"
+#   #           else
+#   #             echo "::set-output name=should_run::false"
+#   #           fi
 
-  deploy-def:
-    # needs: check_run
-    # if: needs.check_run.outputs.should_run == 'true' && (github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
-    if: env.CP_CONF_CHANGED == 'false' && env.JS_CHANGED == 'false'
-    runs-on: kong
-    name: Deploying Kong Configuration
-    environment: play
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2.5.0
-    - name: Setup Node
-      uses: actions/setup-node@v3.5.1
-      with:
-        node-version: "16"
+#   deploy-def:
+#     # needs: check_run
+#     # if: needs.check_run.outputs.should_run == 'true' && (github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
+#     if: env.CP_CONF_CHANGED == 'false' && env.JS_CHANGED == 'false'
+#     runs-on: kong
+#     name: Deploying Kong Configuration
+#     environment: play
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v2.5.0
+#     - name: Setup Node
+#       uses: actions/setup-node@v3.5.1
+#       with:
+#         node-version: "16"
 
-    - name: Display decK Version
-      run: deck version
+#     - name: Display decK Version
+#       run: deck version
 
-    - name: Backup existing configuration for a specific tag
-      run: deck dump -o kong-dev.yaml --tls-skip-verify
-      env:
-        DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-        DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     - name: Backup existing configuration for a specific tag
+#       run: deck dump -o kong-dev.yaml --tls-skip-verify
+#       env:
+#         DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#         DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    - name: Validate Deck Config File
-      run: deck validate -s ./deck
+#     - name: Validate Deck Config File
+#       run: deck validate -s ./deck
 
-    - name: Compare Configurations
-      run: deck diff  -s ./deck --tls-skip-verify
-      env:
-        DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-        DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     - name: Compare Configurations
+#       run: deck diff  -s ./deck --tls-skip-verify
+#       env:
+#         DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#         DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    - name: Apply new configuration
-      run: deck sync  -s ./deck --tls-skip-verify
-      env:
-        DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-        DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     - name: Apply new configuration
+#       run: deck sync  -s ./deck --tls-skip-verify
+#       env:
+#         DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#         DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    - name: Back out changes on failure
-      if: ${{ failure() }}
-      run: deck sync  -s kong-dev.yaml  --tls-skip-verify
-      env:
-        DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-        DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     - name: Back out changes on failure
+#       if: ${{ failure() }}
+#       run: deck sync  -s kong-dev.yaml  --tls-skip-verify
+#       env:
+#         DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#         DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
