test

diff --git a/.github/workflows/js.yml b/.github/workflows/js.yml
--- a/.github/workflows/js.yml
+++ b/.github/workflows/js.yml
@@ -1,84 +1,84 @@
-name: Run js-plugins
-on:
-  push:
-    branches:
-      - 'main'
-    paths:
-      - 'js/**'
-      - 'kong-conf/**'
+# name: Run js-plugins
+# on:
+#   push:
+#     branches:
+#       - 'main'
+#     paths:
+#       - 'js/**'
+#       - 'kong-conf/**'
 
-jobs:
-  deploy-cp-js:
-    runs-on: kong
-    name: Deploying Kong Configuration
-    environment: play
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2.5.0
-    - name: Setup Node
-      uses: actions/setup-node@v3.5.1
-      with:
-        node-version: "16"
-    # - name: Install decK
-    #   run: |
-    #     curl -sL https://github.com/kong/deck/releases/download/v1.5.1/deck_1.5.1_linux_amd64.tar.gz -o deck.tar.gz
-    #     tar -xf deck.tar.gz -C /tmp
-    #     cp /tmp/deck /usr/local/bin/
+# jobs:
+#   deploy-cp-js:
+#     runs-on: kong
+#     name: Deploying Kong Configuration
+#     environment: play
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v2.5.0
+#     - name: Setup Node
+#       uses: actions/setup-node@v3.5.1
+#       with:
+#         node-version: "16"
+#     # - name: Install decK
+#     #   run: |
+#     #     curl -sL https://github.com/kong/deck/releases/download/v1.5.1/deck_1.5.1_linux_amd64.tar.gz -o deck.tar.gz
+#     #     tar -xf deck.tar.gz -C /tmp
+#     #     cp /tmp/deck /usr/local/bin/
 
-    # - name: Display decK Version
-    #   run: deck version
+#     # - name: Display decK Version
+#     #   run: deck version
 
-    # - name: Backup existing configuration for a specific tag
-    #   run: deck dump -o kong-dev.yaml --tls-skip-verify
-    #   env:
-    #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-    #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     # - name: Backup existing configuration for a specific tag
+#     #   run: deck dump -o kong-dev.yaml --tls-skip-verify
+#     #   env:
+#     #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#     #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    # - name: Validate Deck Config File
-    #   run: deck validate -s ./deck
+#     # - name: Validate Deck Config File
+#     #   run: deck validate -s ./deck
 
-    # - name: Compare Configurations
-    #   run: deck diff  -s ./deck --tls-skip-verify
-    #   env:
-    #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-    #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     # - name: Compare Configurations
+#     #   run: deck diff  -s ./deck --tls-skip-verify
+#     #   env:
+#     #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#     #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    # - name: Apply new configuration
-    #   run: deck sync  -s ./deck --tls-skip-verify
-    #   env:
-    #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-    #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     # - name: Apply new configuration
+#     #   run: deck sync  -s ./deck --tls-skip-verify
+#     #   env:
+#     #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#     #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    # - name: Back out changes on failure
-    #   if: ${{ failure() }}
-    #   run: deck sync  -s kong-dev.yaml  --tls-skip-verify
-    #   env:
-    #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
-    #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
+#     # - name: Back out changes on failure
+#     #   if: ${{ failure() }}
+#     #   run: deck sync  -s kong-dev.yaml  --tls-skip-verify
+#     #   env:
+#     #     DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
+#     #     DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
 
-    - name: copyfile-js
-      run: cp -rf ./js/* /usr/local/kong/js-plugins
+#     - name: copyfile-js
+#       run: cp -rf ./js/* /usr/local/kong/js-plugins
 
-    - name: copyfile-backup
-      run: cp -f /etc/kong/kong.conf ./kongbackup.conf 
+#     - name: copyfile-backup
+#       run: cp -f /etc/kong/kong.conf ./kongbackup.conf 
 
-    - name: copyfile-kogconf
-      run: cp -f ./kong-conf/kong.conf /etc/kong/kong.conf
+#     - name: copyfile-kogconf
+#       run: cp -f ./kong-conf/kong.conf /etc/kong/kong.conf
 
-    - name: restart kong
-      run: sudo systemctl restart kong
+#     - name: restart kong
+#       run: sudo systemctl restart kong
 
-    - name: Back kogconf
-      if: ${{ failure() }}
-      run: cp -f ./kongbackup.conf /etc/kong/kong.conf
+#     - name: Back kogconf
+#       if: ${{ failure() }}
+#       run: cp -f ./kongbackup.conf /etc/kong/kong.conf
 
-    - name: restart kong
-      if: ${{ failure() }}
-      run: sudo systemctl restart kong
+#     - name: restart kong
+#       if: ${{ failure() }}
+#       run: sudo systemctl restart kong
 
-    - name: Trigger failure
-      if: ${{ failure() }}
-      continue-on-error: true
-      run: exit 1
+#     - name: Trigger failure
+#       if: ${{ failure() }}
+#       continue-on-error: true
+#       run: exit 1
           
         
