test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -98,9 +98,9 @@ jobs:
       if: ${{ failure() }}
       run: sudo rm -rf *
 
-    - name: Trigger failure
-      if: ${{ failure() }}
-      run: exit 1
+    # - name: Trigger failure
+    #   if: ${{ failure() }}
+    #   run: exit 1
 
   deploy-dp:
     needs: deploy-cp
@@ -160,9 +160,9 @@ jobs:
     #   if: ${{ failure() }}
     #   run: sudo rm -rf *
 
-    - name: Trigger failure
-      if: ${{ failure() }}
-      run: exit 1
+    # - name: Trigger failure
+    #   if: ${{ failure() }}
+    #   run: exit 1
 
   back-cp:
     needs: deploy-dp
